module.exports = {
  printWidth: 80,
  tabWidth: 2,
  trailingComma: "all",
  // singleQuote: true,
  semi: true,
  importOrder: [
    "^@core/(.*)$",
    "^pages/(.*)$",
    "^components/(.*)$",
    "^hooks/(.*)$",
    "^types/(.*)$",
    "^libs/(.*)$",
    "^@server/(.*)$",
    "^@ui/(.*)$",
    "^[./]",
  ],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
};
